name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install compiler
      run: wget https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0/protoc-3.20.0-linux-x86_64.zip && unzip protoc-3.20.0-linux-x86_64.zip && export PATH=$PATH:`pwd`/protoc-3.20.0-linux-x86_64/bin

    - name: Set up buf
      run: BIN="/usr/local/bin" && VERSION="1.3.1" && curl -sSL "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" -o "${BIN}/buf" && chmod +x "${BIN}/buf"
      
    - name: Install proto plugin
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      
    - name: Generate
      run: make generate
